### ISSUE TITLE
Calibre OPDS client fails in calibre 6

### ISSUE THREAD

**Issue by PiperKev** [steinarb/opds-reader#32]
calibre just upgraded to version 6.0.0, and Calibre OPDS client fails with:

calibre, version 6.0.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QHeaderView' has no attribute 'Stretch'

calibre 6.0  embedded-python: True
Linux-5.15.0-33-generic-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.15.0-33-generic', '#34~20.04.1-Ubuntu SMP Thu May 19 15:51:16 UTC 2022')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 49, 0) && Find Duplicates (1, 9, 5) && Goodreads (1, 5, 3) && Goodreads Sync (1, 15, 1) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Kindle hi-res covers (0, 5, 0) && OPDS Client (1, 0, 0) && Obok DeDRM (7, 2, 1) && Search The Internet (1, 8, 1) && Standard Ebooks (1, 0, 0)
Traceback (most recent call last):
  File "calibre_plugins.opds_client.ui", line 24, in show_dialog
    d = OpdsDialog(self.gui, self.qaction.icon(), do_user_config)
  File "calibre_plugins.opds_client.main", line 105, in __init__
    self.library_view.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
AttributeError: type object 'QHeaderView' has no attribute 'Stretch'

On the calibre website, under "What's New" there's this:

"Because calibre has now moved to Qt 6, some third party plugins will no longer work, until they are also ported to Qt 6. Fortunately, plugin developers were given over half a year to port their plugins, so most have already been ported."

**Comment by PiperKev** [comment]
No worries, I just reverted to 5.44.  There's nothing in calibre 6 that's an urgent need for me.

**Comment by OdinVex** [comment]
Can confirm PR #33 fixes.

**Comment by PiperKev** [comment]
> Can confirm PR #33 fixes.

I confirmed that it works with calibre 6.1.0.

**Comment by steinarb** [comment]
PR merged! Thanks to @mquin !
